version: '3.8'
services:

  stats-server:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=Kate
      - POSTGRES_PASSWORD=purrrrrr

  stats-db:
    image: postgres:14
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=Kate
      - POSTGRES_PASSWORD=purrrrrr

  ewm-service:
    build: ./server
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/server
      - POSTGRES_USER=Kate
      - POSTGRES_PASSWORD=purrrrrr

  ewm-db:
    image: postgres:14
    container_name: ewm-service-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=Kate
      - POSTGRES_PASSWORD=purrrrrr