CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(256)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(256)                            NOT NULL,
    CONSTRAINT category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    title VARCHAR(128)                          NOT NULL,
    annotation VARCHAR(512)                     NOT NULL,
    description VARCHAR(1024)                   NOT NULL,
    category_id BIGINT,
    created TIMESTAMP,
    event_date TIMESTAMP,
    initiator_id BIGINT                         NOT NULL,
    paid BOOLEAN,
    participant_limit BIGINT DEFAULT 0          NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOLEAN,
    state VARCHAR(20)                           NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_EVENT_ON_USER FOREIGN KEY (initiator_id) REFERENCES users (id)
 );

CREATE TABLE IF NOT EXISTS event_locations
(
    event_id BIGINT                             NOT NULL
        CONSTRAINT event_id_location REFERENCES events
            ON UPDATE CASCADE ON DELETE CASCADE,
    lat      NUMERIC                            NOT NULL,
    lon      NUMERIC                            NOT NULL,
    CONSTRAINT LOCATION FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                        NOT NULL,
    requester_id BIGINT                        NOT NULL,
    status       VARCHAR,
    created      TIMESTAMP,
    CONSTRAINT pk_request PRIMARY KEY (id),
    UNIQUE (requester_id, event_id),
    CONSTRAINT REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT EVENT FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(256)                        NOT NULL,
    pinned BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    event_id       BIGINT                               NOT NULL,
    compilation_id BIGINT                               NOT NULL,
    CONSTRAINT COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT EVENT FOREIGN KEY (event_id) REFERENCES events (id)
);