CREATE TABLE IF NOT EXISTS STATS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    APP VARCHAR(256)                            NOT NULL,
    URI VARCHAR(48)                             NOT NULL,
    IP VARCHAR(24)                              NOT NULL,
    TIMESTAMP TIMESTAMP                         NOT NULL,
    CONSTRAINT PK_STATS PRIMARY KEY (ID)
);